### ISSUE TITLE
Failed to get running on Windows...

### ISSUE THREAD

**Issue by rashuge** [brbeaird/SmartThings-MyQ-Edge#12]
I followed the instructions posted for the Windows executable.  I copied the executable to a location on my drive.  I executed it from the command line as described.  I have put in exceptions in the firewall and have tested it with the firewall disabled.  The machine is on the same network on the MyQ devices and the hub...all the same subnet and IP range.  I have a specific port locked in but other than that, I just try to run the executable.  Somewhere in your documentation it referenced using a .json file to hold the credentials but I cannot find the file or the example.  I can never get the devices to show up in the list of nearby devices.  Anything you can do to help would be appreciated.

**Comment by brbeaird** [comment]
I pushed an update over the weekend that may be helpful for you if you want to try again.

There is no longer a json config file for the server - that is now completely handled by the Edge driver in the device settings and info is passed from the Hub to the Bridge server.

**Comment by rashuge** [comment]
I checked again, it appeared to pull in the controller.  It shows my two devices in the controller.  I cannot do anything else from there though.  I removed the MyQ SmartApp.  I still don't see the doors as objects.

**Comment by brbeaird** [comment]
Did you follow the steps to add the Edge driver and get the MyQ-Connector device created via the mobile app and enter your credentials there?

**Comment by rashuge** [comment]
I had deleted the MyQ Smart App after I setup the controller with credentials, it caused issues with communication. I did a service restart and waited 10 minutes,it is working well now. Thanks.
